### ISSUE TITLE
Wrong secret is used in `import.yaml`

### ISSUE THREAD

**Issue by Bisaloo** [krlmlr/actions-sync#10]
Hi,

Thanks for making this project available to the community, it looks amazing. I'm currently experimenting with it in https://github.com/covid19-forecast-hub-europe/actions-sync. My `import.yaml` runs were initially all failing with the following error:

>  ! [remote rejected] HEAD -> covid19-forecast-hub-europe/covid19-forecast-hub-europe (refusing to allow a GitHub App to create or update workflow `.github/workflows/push-on-change.yaml` without `workflows` permission)

I triple checked my secret was correctly named and I had indeed the `workflow` permission but to no avail.

The fix that did work was https://github.com/covid19-forecast-hub-europe/actions-sync/commit/073a468decfd26770334f038ee72de8ab9c68b23, i.e., using the correct secret when checking out the repo. It looks like otherwise, git will try to always use the default, scope-limited, `GITHUB_TOKEN` secret for everything, even though [you explicitly ask](https://github.com/krlmlr/actions-sync/blob/f47d628dd91dd44e8d2733ccd017197639246e84/.github/workflows/import.yaml#L57) to use `TOKEN_KEYS`.

I can submit a PR if you wish but I figured I would open an issue first so you can verify my conclusions by yourself.

**Comment by krlmlr** [comment]
Thanks. Perhaps some internals have changed. The patch looks good to me, happy to review a PR.

**Comment by krlmlr** [comment]
Seems good now, thanks.
