### ISSUE TITLE
Use devel version of `{pak}` for package installation

### ISSUE THREAD

**Issue by IndrajeetPatil** [krlmlr/actions-sync#14]
In `workflows/install/action.yml`, can we use devel version of `{pak}`?

A few build failures seem to be due to failure to install a dependency on an older R version, but it's difficult to figure out which one by the error message produced by CRAN version of `{pak}`. The devel version of `{pak}` provides a more helpful message.

So, change the following

```r
    - uses: r-lib/actions/setup-r-dependencies@v2
      env:
        GITHUB_PAT: ${{ inputs.token }}
      with:
        needs: ${{ inputs.needs }}
        extra-packages: ${{ inputs.extra-packages }} ${{ matrix.config.covr && 'any::covr' }} ${{ steps.get-extra.outputs.packages }}
        cache-version: ${{ inputs.cache-version }}
```

to

```r
    - uses: r-lib/actions/setup-r-dependencies@v2
      env:
        GITHUB_PAT: ${{ inputs.token }}
      with:
        pak-version: devel
        needs: ${{ inputs.needs }}
        extra-packages: ${{ inputs.extra-packages }} ${{ matrix.config.covr && 'any::covr' }} ${{ steps.get-extra.outputs.packages }}
        cache-version: ${{ inputs.cache-version }}
```

for all repos.

**Comment by krlmlr** [comment]
Sure, sounds good. Would you like to implement?

- Clone, create work trees
- Change in `base`, commit
- Cherry-pick in all worktrees
- Push
- Clean up

**Comment by IndrajeetPatil** [comment]
Yes, I can try to do this. Just need to overcome my `git` diffidence.

**Comment by IndrajeetPatil** [comment]
I managed to do the first three steps, but then I can't push due to the following issue:

![Screenshot 2022-10-12 at 22 31 25](https://user-images.githubusercontent.com/11330453/195441952-e3c7024d-2fee-4103-8db3-59489e4df0fa.png)

**Comment by IndrajeetPatil** [comment]
Maybe I don't have the necessary permissions to push to remote repositories, only to the central repository?

**Comment by krlmlr** [comment]
Thanks, this is weird. Can you try using an SSH remote instead?

**Comment by IndrajeetPatil** [comment]
Seems to have worked?
