### ISSUE TITLE
Avoid PR flood when snapshots change due to updated dependencies

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/actions-sync#15]
We need to apply 152628bd9dc36c1ea9e693dd2bc4c235280d1e8e and 346b967bce1ef6d5a4f8e2b5485222de0441c1c4 to all repositories, to avoid creating too many PRs when snapshot tests change due to an update in the dependencies.

@IndrajeetPatil: can you please take care of it?

**Comment by IndrajeetPatil** [comment]
Sure, I can have a look at it.
