### ISSUE TITLE
Consistently use `ubuntu-latest`?

### ISSUE THREAD

**Issue by IndrajeetPatil** [krlmlr/actions-sync#16]
Currently, some actions use `ubuntu-18.04`, while others `ubuntu-latest`.

@krlmlr If you agree, I can make this change.

**Comment by krlmlr** [comment]
Thanks. I have a slight preference for fixing the version (e.g. 20.04 instead of "latest"). Will everything continue to work when we upgrade to 20.04? Should we maybe even deliberately test things on older images too?

**Comment by krlmlr** [comment]
Let's switch to Ubuntu 22. We also need to switch to Node 16, e.g., https://github.com/r-dbi/DBItest/actions/runs/3270079958. Can we do this in one swoop?

Tests for Ubuntu 20.04 and Ubuntu 18.04 should be part of #23.

**Comment by IndrajeetPatil** [comment]
> We also need to switch to Node 16

IINM, those warnings are coming from `r-lib/actions`: https://github.com/r-lib/actions/issues/626
We don't specify Node version anywhere.

**Comment by krlmlr** [comment]
Do we need to use a newer tag for actions/checkout?

**Comment by IndrajeetPatil** [comment]
No, I don't think we need to.

**Comment by krlmlr** [comment]
I'm glad we didn't use ubuntu-latest because R is no longer available by default on ubuntu-24.04 and some workflows rely on it.
