### ISSUE TITLE
Avoid set-output

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/actions-sync#21]
About to be deprecated: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ .

**Comment by IndrajeetPatil** [comment]
Will this work?

---

From

https://github.com/krlmlr/actions-sync/blob/c73cead9d6d35b70668b38a35c86d2665a44bac4/template/.github/workflows/push-on-change.yaml#L29

to

```yaml
echo "slug=$(echo $GITHUB_REF | sed 's#refs/heads/##')" >> $GITHUB_OUTPUT
```

---

From

https://github.com/krlmlr/actions-sync/blob/c73cead9d6d35b70668b38a35c86d2665a44bac4/.github/workflows/import.yaml#L40

to

```yaml
echo "exists=$(git branch --list origin/${{ github.event.inputs.remote_repo }})" >> $GITHUB_OUTPUT
```

**Comment by krlmlr** [comment]
I don't know, it's worth a try.

**Comment by krlmlr** [comment]
Done now.
