### ISSUE TITLE
Workflow that tests without suggested dependencies

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/actions-sync#22]
A matrix for each suggested and enhanced package, where we omit only the corresponding package in each run.

Example: suggests rlang, vctrs, igraph.

Three runs, in a matrix:

1. without rlang + vctrs
2. without vctrs
3. without igraph

https://www.cynkra.com/blog/2020-12-23-dynamic-gha/

**Comment by IndrajeetPatil** [comment]
> A matrix for each suggested and enhanced package, where we omit only the corresponding package in each run.

Why omitting each package per run is better than omitting all of them in a single run, like in the [check-no-suggests](https://github.com/r-lib/actions/blob/v2-branch/examples/check-no-suggests.yaml) workflow?

If the package passes the latter workflow, it will pass every single run of the former workflows.

**Comment by krlmlr** [comment]
Are you sure?

**Comment by IndrajeetPatil** [comment]
Yes, I am fairly certain.

---

Let's say a package suggests `{rlang}`, `{vctrs}`, `{igraph}`. 

`R-CMD-Check-hard` workflow installs _none_ of these suggested packages and checks if the package passes `R CMD check`. 

If the package succeeds on this workflow, it means that
- it will pass `R CMD check` if _all_ of its suggested dependencies are missing
- this, of course, means that it will also pass `R CMD check` if _any_ one of its suggested dependencies is missing

---

Does that make sense?

**Comment by krlmlr** [comment]
I'd be interested in catching the following cases:

```r
test_that("example", {
  skip_if_not_installed("vctrs")
  igraph::some_igraph_fun(vctrs::some_vctrs_fun(...))
})
```

Can we do this without a matrix?

**Comment by IndrajeetPatil** [comment]
No, it won't. 

But I am wondering how likely are we to run into contexts like these, and if we are over-engineering a solution for a problem that most packages will never run into. The version of this workflow where all suggested deps are removed is likely to be sufficient for most packages.

To get started, I am trying the non-dynamic version in `{dm}` (https://github.com/cynkra/dm/pull/1659).

We can come back to the dynamic version later.

**Comment by IndrajeetPatil** [comment]
https://github.com/krlmlr/actions-sync/pull/35 targets this issue.

As seen in https://github.com/cynkra/dm/pull/1659, this workflow can indeed capture most of the missing instances of conditional usage of suggested deps.

**Comment by krlmlr** [comment]
This has been available for a while, works for me.
