### ISSUE TITLE
Fix dev workflows

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/actions-sync#25]
DBItest now has the correct version.

**Comment by IndrajeetPatil** [comment]
Relevant commit: https://github.com/r-dbi/DBItest/commit/d2c1a1dea8a32d4c3594af87f2577403ef334c9f

**Comment by IndrajeetPatil** [comment]
Closed in https://github.com/krlmlr/actions-sync/commit/994462a69d7fdf10a001fd7a985b0a9a8a616439
