### ISSUE TITLE
Upgrade to `checkout@v3` and `cache@v3`

### ISSUE THREAD

**Issue by IndrajeetPatil** [krlmlr/actions-sync#27]
We are already using `actions/checkout@v3`, but not consistently ([e.g.](https://github.com/krlmlr/actions-sync/blob/c73cead9d6d35b70668b38a35c86d2665a44bac4/.github/workflows/import.yaml#L22)).

**Comment by krlmlr** [comment]
Can be cherry-picked from f0fbc2c9b43765cbfd8df20299c17f8e53565418, I force-pushed the base branch.

**Comment by IndrajeetPatil** [comment]
Thanks! Done.
