### ISSUE TITLE
Is `push-on-change.yaml` supposed to be deleted?

### ISSUE THREAD

**Issue by IndrajeetPatil** [krlmlr/actions-sync#29]
While trying to cherry-pick f2e46beabdb161c1390da2b7f00b5c5fe063c7af, I am running into merge conflicts because in most (all?) remote repositories, [push-on-change](https://github.com/krlmlr/actions-sync/blob/base/style/.github/workflows/push-on-change.yaml) workflow has been deleted. Should it also be deleted in the `base`-branch here?

**Comment by krlmlr** [comment]
I'm pretty sure we don't need that many push-on-change.yaml. Cleaned in f56c31a441ea7c6fd397022f772bbae63d02881b.

The file is copied automatically from https://github.com/krlmlr/actions-sync/blob/main/template/.github/workflows/push-on-change.yaml . Fixing there should be sufficient.
